-- MySQL Script generated by MySQL Workbench
-- Wed 09 Mar 2016 23:17:07 GMT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `surname` VARCHAR(45) NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idUsers`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RSPi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RSPi` (
  `idRSPi` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idUserOwner` INT NOT NULL COMMENT '',
  `idSystem` INT NOT NULL COMMENT '',
  `onlineStatus` TINYINT(1) NOT NULL COMMENT '',
  `pin1` TINYINT(1) NOT NULL COMMENT '',
  `pin2` TINYINT(1) NOT NULL COMMENT '',
  `pin3` TINYINT(1) NOT NULL COMMENT '',
  PRIMARY KEY (`idRSPi`)  COMMENT '',
  INDEX `fk_RSPi_Users_idx` (`idUserOwner` ASC)  COMMENT '',
  CONSTRAINT `fk_RSPi_Users`
    FOREIGN KEY (`idUserOwner`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`WebServLog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`WebServLog` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idUser` INT NULL COMMENT '',
  `idRSPi` INT NULL COMMENT '',
  `event` VARCHAR(100) NOT NULL COMMENT '',
  `date` DATE NOT NULL COMMENT '',
  `time` TIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_WebServLog_Users1_idx` (`idUser` ASC)  COMMENT '',
  INDEX `fk_WebServLog_RSPi1_idx` (`idRSPi` ASC)  COMMENT '',
  CONSTRAINT `fk_WebServLog_Users1`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WebServLog_RSPi1`
    FOREIGN KEY (`idRSPi`)
    REFERENCES `mydb`.`RSPi` (`idRSPi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CommServLog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CommServLog` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idRSPi` INT NULL COMMENT '',
  `idUsers` INT NULL COMMENT '',
  `event` VARCHAR(100) NOT NULL COMMENT '',
  `date` DATE NOT NULL COMMENT '',
  `time` TIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_CommServLog_RSPi1_idx` (`idRSPi` ASC)  COMMENT '',
  INDEX `fk_CommServLog_Users1_idx` (`idUsers` ASC)  COMMENT '',
  CONSTRAINT `fk_CommServLog_RSPi1`
    FOREIGN KEY (`idRSPi`)
    REFERENCES `mydb`.`RSPi` (`idRSPi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CommServLog_Users1`
    FOREIGN KEY (`idUsers`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RSPi_Rights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RSPi_Rights` (
  `idUserApproved` INT NOT NULL COMMENT '',
  `idRSPi` INT NOT NULL COMMENT '',
  INDEX `fk_Users_has_RSPi_RSPi1_idx` (`idRSPi` ASC)  COMMENT '',
  INDEX `fk_Users_has_RSPi_Users1_idx` (`idUserApproved` ASC)  COMMENT '',
  CONSTRAINT `fk_Users_has_RSPi_Users1`
    FOREIGN KEY (`idUserApproved`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_RSPi_RSPi1`
    FOREIGN KEY (`idRSPi`)
    REFERENCES `mydb`.`RSPi` (`idRSPi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
